# Generated by Django 3.1.1 on 2020-09-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droneManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='x',
            new_name='x_pos',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='y',
            new_name='y_pos',
        ),
    ]
